version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: my_toronto_time
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  go-app:
    build: .
    container_name: go-toronto-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=my_toronto_time

volumes:
  mysql-data:
    driver: local
